### ISSUE TITLE
POSIX shell

### ISSUE THREAD

**Issue by jobbautista9** [psqli/pcmsh#1]
When running the script using `dash` (which is Debian's default non-interactive shell), `dash` complains about bad substitution in line 49. Seems like your shell script is using some bashisms according to `checkbashisms`:

    possible bashism in pcm.sh line 48 ('$[' should be '$(('):
                    i=$[$i-2]
    possible bashism in pcm.sh line 49 (${foo:3[:1]}):
                    echo -n ${1:$i:2}

Please fix this by either rewriting it to be POSIX compliant, or changing the shebang to `#/bin/bash`.

**Comment by psqli** [comment]
Thank you! Should be fixed by 0a7da0f49aebbaefffc392cb4bd8f4d52f5cb8cd
